
# BOARD     							= BLCON
# CORELIB   							= -lstm32f37x
BOARD     							= M4_WHITE
CORELIB   							= -lstm32f37x_m4

# FLASH_METHOD						= SERIAL
EEPROM_NUMBER_VALUES 		= 0

include $(STM32DIR)/project.mk


